[MeterLine0]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*0)+#LineOffSet#
[MeterLine1]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*1)+#LineOffSet#
[MeterLine2]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*2)+#LineOffSet#
[MeterLine3]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*3)+#LineOffSet#
[MeterLine4]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*4)+#LineOffSet#
[MeterLine5]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*5)+#LineOffSet#
[MeterLine6]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*6)+#LineOffSet#
[MeterLine7]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*7)+#LineOffSet#
[MeterLine8]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*8)+#LineOffSet#
[MeterLine9]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*9)+#LineOffSet#
[MeterLine10]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*10)+#LineOffSet#
[MeterLine11]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*11)+#LineOffSet#
[MeterLine12]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*12)+#LineOffSet#
[MeterLine13]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*13)+#LineOffSet#
[MeterLine14]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*14)+#LineOffSet#
[MeterLine15]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*15)+#LineOffSet#
[MeterLine16]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*16)+#LineOffSet#
[MeterLine17]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*17)+#LineOffSet#
[MeterLine18]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*18)+#LineOffSet#
[MeterLine19]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*19)+#LineOffSet#
[MeterLine20]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*20)+#LineOffSet#
[MeterLine21]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*21)+#LineOffSet#
[MeterLine22]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*22)+#LineOffSet#
[MeterLine23]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*23)+#LineOffSet#
[MeterLine24]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*24)+#LineOffSet#
[MeterLine25]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*25)+#LineOffSet#
[MeterLine26]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*26)+#LineOffSet#
[MeterLine27]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*27)+#LineOffSet#
[MeterLine28]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*28)+#LineOffSet#
[MeterLine29]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*29)+#LineOffSet#
[MeterLine30]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*30)+#LineOffSet#
[MeterLine31]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*31)+#LineOffSet#
[MeterLine32]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*32)+#LineOffSet#
[MeterLine33]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*33)+#LineOffSet#
[MeterLine34]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*34)+#LineOffSet#
[MeterLine35]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*35)+#LineOffSet#
[MeterLine36]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*36)+#LineOffSet#
[MeterLine37]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*37)+#LineOffSet#
[MeterLine38]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*38)+#LineOffSet#
[MeterLine39]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*39)+#LineOffSet#
[MeterLine40]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*40)+#LineOffSet#
[MeterLine41]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*41)+#LineOffSet#
[MeterLine42]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*42)+#LineOffSet#
[MeterLine43]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*43)+#LineOffSet#
[MeterLine44]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*44)+#LineOffSet#
[MeterLine45]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*45)+#LineOffSet#
[MeterLine46]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*46)+#LineOffSet#
[MeterLine47]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*47)+#LineOffSet#
[MeterLine48]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*48)+#LineOffSet#
[MeterLine49]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*49)+#LineOffSet#
[MeterLine50]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*50)+#LineOffSet#
[MeterLine51]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*51)+#LineOffSet#
[MeterLine52]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*52)+#LineOffSet#
[MeterLine53]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*53)+#LineOffSet#
[MeterLine54]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*54)+#LineOffSet#
[MeterLine55]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*55)+#LineOffSet#
[MeterLine56]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*56)+#LineOffSet#
[MeterLine57]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*57)+#LineOffSet#
[MeterLine58]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*58)+#LineOffSet#
[MeterLine59]
Meter = Roundline
UpdateDivider = -1
MeterStyle = DividerStyle
StartAngle = (#lineAngle#*59)+#LineOffSet#