[MeterGradient0]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT0
ImageName = ../FFTGradient.png
[MeterFFT0]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand0
Solid = 0
ControlLength = 1
ControlAngle = 0
LengthShift = #barHeight#
X = 0
Y = 0
H = 220
W = 220
LineWidth = #barWidth#
LineStart = (#skinWidth#/2)-46
LineLength = (#skinWidth#/2)-43
StartAngle = ((2*PI)*0.576)
LineColor = 255, 255, 255, ([MeasureBand0]*255)
AntiAlias = 1
DynamicVariables = 1


[MeterGradient1]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT1
ImageName = ../FFTGradient.png
[MeterFFT1]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand1
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.006))
LineColor = 255, 255, 255, ([MeasureBand1]*255)

[MeterGradient2]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT2
ImageName = ../FFTGradient.png
[MeterFFT2]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand2
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.012))
LineColor = 255, 255, 255, ([MeasureBand2]*255)

[MeterGradient3]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT3
ImageName = ../FFTGradient.png
[MeterFFT3]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand3
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.018))
LineColor = 255, 255, 255, ([MeasureBand3]*255)

[MeterGradient4]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT4
ImageName = ../FFTGradient.png
[MeterFFT4]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand4
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.024))
LineColor = 255, 255, 255, ([MeasureBand4]*255)

[MeterGradient5]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT5
ImageName = ../FFTGradient.png
[MeterFFT5]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand5
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.030))
LineColor = 255, 255, 255, ([MeasureBand5]*255)

[MeterGradient6]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT6
ImageName = ../FFTGradient.png
[MeterFFT6]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand6
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.036))
LineColor = 255, 255, 255, ([MeasureBand6]*255)

[MeterGradient7]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT7
ImageName = ../FFTGradient.png
[MeterFFT7]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand7
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.042))
LineColor = 255, 255, 255, ([MeasureBand7]*255)

[MeterGradient8]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT8
ImageName = ../FFTGradient.png
[MeterFFT8]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand8
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.048))
LineColor = 255, 255, 255, ([MeasureBand8]*255)

[MeterGradient9]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT9
ImageName = ../FFTGradient.png
[MeterFFT9]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand9
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.054))
LineColor = 255, 255, 255, ([MeasureBand9]*255)

[MeterGradient10]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT10
ImageName = ../FFTGradient.png
[MeterFFT10]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand10
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.060))
LineColor = 255, 255, 255, ([MeasureBand10]*255)

[MeterGradient11]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT11
ImageName = ../FFTGradient.png
[MeterFFT11]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand11
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.066))
LineColor = 255, 255, 255, ([MeasureBand11]*255)

[MeterGradient12]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT12
ImageName = ../FFTGradient.png
[MeterFFT12]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand12
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.072))
LineColor = 255, 255, 255, ([MeasureBand12]*255)

[MeterGradient13]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT13
ImageName = ../FFTGradient.png
[MeterFFT13]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand13
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.078))
LineColor = 255, 255, 255, ([MeasureBand13]*255)

[MeterGradient14]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT14
ImageName = ../FFTGradient.png
[MeterFFT14]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand14
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.084))
LineColor = 255, 255, 255, ([MeasureBand14]*255)

[MeterGradient15]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT15
ImageName = ../FFTGradient.png
[MeterFFT15]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand15
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.090))
LineColor = 255, 255, 255, ([MeasureBand15]*255)

[MeterGradient16]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT16
ImageName = ../FFTGradient.png
[MeterFFT16]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand16
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.096))
LineColor = 255, 255, 255, ([MeasureBand16]*255)

[MeterGradient17]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT17
ImageName = ../FFTGradient.png
[MeterFFT17]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand17
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.102))
LineColor = 255, 255, 255, ([MeasureBand17]*255)

[MeterGradient18]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT18
ImageName = ../FFTGradient.png
[MeterFFT18]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand18
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.108))
LineColor = 255, 255, 255, ([MeasureBand18]*255)

[MeterGradient19]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT19
ImageName = ../FFTGradient.png
[MeterFFT19]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand19
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.114))
LineColor = 255, 255, 255, ([MeasureBand19]*255)

[MeterGradient20]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT20
ImageName = ../FFTGradient.png
[MeterFFT20]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand20
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.120))
LineColor = 255, 255, 255, ([MeasureBand20]*255)

[MeterGradient21]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT21
ImageName = ../FFTGradient.png
[MeterFFT21]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand21
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.126))
LineColor = 255, 255, 255, ([MeasureBand21]*255)

[MeterGradient22]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT22
ImageName = ../FFTGradient.png
[MeterFFT22]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand22
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.132))
LineColor = 255, 255, 255, ([MeasureBand22]*255)

[MeterGradient23]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT23
ImageName = ../FFTGradient.png
[MeterFFT23]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand23
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.138))
LineColor = 255, 255, 255, ([MeasureBand23]*255)

[MeterGradient24]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT24
ImageName = ../FFTGradient.png
[MeterFFT24]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand24
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.144))
LineColor = 255, 255, 255, ([MeasureBand24]*255)

[MeterGradient25]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT25
ImageName = ../FFTGradient.png
[MeterFFT25]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand25
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.150))
LineColor = 255, 255, 255, ([MeasureBand25]*255)

[MeterGradient26]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT26
ImageName = ../FFTGradient.png
[MeterFFT26]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand26
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.156))
LineColor = 255, 255, 255, ([MeasureBand26]*255)

[MeterGradient27]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT27
ImageName = ../FFTGradient.png
[MeterFFT27]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand27
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.162))
LineColor = 255, 255, 255, ([MeasureBand27]*255)

[MeterGradient28]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT28
ImageName = ../FFTGradient.png
[MeterFFT28]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand28
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.168))
LineColor = 255, 255, 255, ([MeasureBand28]*255)

[MeterGradient29]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT29
ImageName = ../FFTGradient.png
[MeterFFT29]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand29
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.174))
LineColor = 255, 255, 255, ([MeasureBand29]*255)

[MeterGradient30]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT30
ImageName = ../FFTGradient.png
[MeterFFT30]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand30
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.180))
LineColor = 255, 255, 255, ([MeasureBand30]*255)

[MeterGradient31]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT31
ImageName = ../FFTGradient.png
[MeterFFT31]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand31
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.186))
LineColor = 255, 255, 255, ([MeasureBand31]*255)

[MeterGradient32]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT32
ImageName = ../FFTGradient.png
[MeterFFT32]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand32
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.192))
LineColor = 255, 255, 255, ([MeasureBand32]*255)

[MeterGradient33]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT33
ImageName = ../FFTGradient.png
[MeterFFT33]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand33
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.198))
LineColor = 255, 255, 255, ([MeasureBand33]*255)

[MeterGradient34]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT34
ImageName = ../FFTGradient.png
[MeterFFT34]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand34
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.204))
LineColor = 255, 255, 255, ([MeasureBand34]*255)

[MeterGradient35]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT35
ImageName = ../FFTGradient.png
[MeterFFT35]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand35
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.210))
LineColor = 255, 255, 255, ([MeasureBand35]*255)

[MeterGradient36]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT36
ImageName = ../FFTGradient.png
[MeterFFT36]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand36
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.216))
LineColor = 255, 255, 255, ([MeasureBand36]*255)

[MeterGradient37]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT37
ImageName = ../FFTGradient.png
[MeterFFT37]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand37
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.222))
LineColor = 255, 255, 255, ([MeasureBand37]*255)

[MeterGradient38]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT38
ImageName = ../FFTGradient.png
[MeterFFT38]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand38
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.228))
LineColor = 255, 255, 255, ([MeasureBand38]*255)

[MeterGradient39]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT39
ImageName = ../FFTGradient.png
[MeterFFT39]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand39
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.234))
LineColor = 255, 255, 255, ([MeasureBand39]*255)

[MeterGradient40]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT40
ImageName = ../FFTGradient.png
[MeterFFT40]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand40
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.240))
LineColor = 255, 255, 255, ([MeasureBand40]*255)

[MeterGradient41]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT41
ImageName = ../FFTGradient.png
[MeterFFT41]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand41
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.246))
LineColor = 255, 255, 255, ([MeasureBand41]*255)

[MeterGradient42]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT42
ImageName = ../FFTGradient.png
[MeterFFT42]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand42
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.252))
LineColor = 255, 255, 255, ([MeasureBand42]*255)

[MeterGradient43]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT43
ImageName = ../FFTGradient.png
[MeterFFT43]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand43
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.258))
LineColor = 255, 255, 255, ([MeasureBand43]*255)

[MeterGradient44]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT44
ImageName = ../FFTGradient.png
[MeterFFT44]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand44
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.264))
LineColor = 255, 255, 255, ([MeasureBand44]*255)

[MeterGradient45]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT45
ImageName = ../FFTGradient.png
[MeterFFT45]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand45
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.270))
LineColor = 255, 255, 255, ([MeasureBand45]*255)

[MeterGradient46]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT46
ImageName = ../FFTGradient.png
[MeterFFT46]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand46
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.276))
LineColor = 255, 255, 255, ([MeasureBand46]*255)

[MeterGradient47]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT47
ImageName = ../FFTGradient.png
[MeterFFT47]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand47
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.282))
LineColor = 255, 255, 255, ([MeasureBand47]*255)

[MeterGradient48]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT48
ImageName = ../FFTGradient.png
[MeterFFT48]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand48
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.288))
LineColor = 255, 255, 255, ([MeasureBand48]*255)

[MeterGradient49]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT49
ImageName = ../FFTGradient.png
[MeterFFT49]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand49
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.294))
LineColor = 255, 255, 255, ([MeasureBand49]*255)

[MeterGradient50]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT50
ImageName = ../FFTGradient.png
[MeterFFT50]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand50
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.300))
LineColor = 255, 255, 255, ([MeasureBand50]*255)

[MeterGradient51]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT51
ImageName = ../FFTGradient.png
[MeterFFT51]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand51
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.306))
LineColor = 255, 255, 255, ([MeasureBand51]*255)

[MeterGradient52]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT52
ImageName = ../FFTGradient.png
[MeterFFT52]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand52
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.312))
LineColor = 255, 255, 255, ([MeasureBand52]*255)

[MeterGradient53]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT53
ImageName = ../FFTGradient.png
[MeterFFT53]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand53
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.318))
LineColor = 255, 255, 255, ([MeasureBand53]*255)

[MeterGradient54]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT54
ImageName = ../FFTGradient.png
[MeterFFT54]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand54
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.324))
LineColor = 255, 255, 255, ([MeasureBand54]*255)

[MeterGradient55]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT55
ImageName = ../FFTGradient.png
[MeterFFT55]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand55
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.330))
LineColor = 255, 255, 255, ([MeasureBand55]*255)

[MeterGradient56]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT56
ImageName = ../FFTGradient.png
[MeterFFT56]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand56
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.336))
LineColor = 255, 255, 255, ([MeasureBand56]*255)

[MeterGradient57]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT57
ImageName = ../FFTGradient.png
[MeterFFT57]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand57
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.342))
LineColor = 255, 255, 255, ([MeasureBand57]*255)

[MeterGradient58]
Meter = Image
W = 220
H = 220
UpdateDivider = -1
Container = MeterFFT58
ImageName = ../FFTGradient.png
[MeterFFT58]
Meter = Roundline
Group = AudioGroup
MeasureName = MeasureBand58
MeterStyle = MeterFFT0
StartAngle = ((2*PI)*(0.576 + 0.348))
LineColor = 255, 255, 255, ([MeasureBand58]*255)