[MeasureBand0]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 0
[MeasureBand1]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 1
[MeasureBand2]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 2
[MeasureBand3]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 3
[MeasureBand4]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 4
[MeasureBand5]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 5
[MeasureBand6]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 6
[MeasureBand7]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 7
[MeasureBand8]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 8
[MeasureBand9]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 9
[MeasureBand10]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 10
[MeasureBand11]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 11
[MeasureBand12]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 12
[MeasureBand13]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 13
[MeasureBand14]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 14
[MeasureBand15]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 15
[MeasureBand16]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 16
[MeasureBand17]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 17
[MeasureBand18]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 18
[MeasureBand19]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 19
[MeasureBand20]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 20
[MeasureBand21]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 21
[MeasureBand22]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 22
[MeasureBand23]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 23
[MeasureBand24]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 24
[MeasureBand25]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 25
[MeasureBand26]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 26
[MeasureBand27]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 27
[MeasureBand28]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 28
[MeasureBand29]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 29
[MeasureBand30]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 30
[MeasureBand31]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 31
[MeasureBand32]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 32
[MeasureBand33]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 33
[MeasureBand34]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 34
[MeasureBand35]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 35
[MeasureBand36]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 36
[MeasureBand37]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 37
[MeasureBand38]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 38
[MeasureBand39]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 39
[MeasureBand40]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 40
[MeasureBand41]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 41
[MeasureBand42]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 42
[MeasureBand43]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 43
[MeasureBand44]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 44
[MeasureBand45]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 45
[MeasureBand46]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 46
[MeasureBand47]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 47
[MeasureBand48]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 48
[MeasureBand49]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 49
[MeasureBand50]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 50
[MeasureBand51]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 51
[MeasureBand52]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 52
[MeasureBand53]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 53
[MeasureBand54]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 54
[MeasureBand55]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 55
[MeasureBand56]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 56
[MeasureBand57]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 57
[MeasureBand58]
Measure = Plugin
Group = AudioGroup
Plugin = AudioLevel
Parent = MeasureAudio
Channel = #barCha#
Type = #barType#
AverageSize = #barAvg#
BandIdx = 58
