;Right-hand RMS
[MeterRMSLineL0]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL1]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*1)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL2]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*2)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL3]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*3)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL4]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*4)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL5]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*5)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL6]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*6)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL7]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*7)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL8]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*8)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL9]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*9)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineL10]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*10)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL11]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*11)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL12]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*12)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL13]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*13)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL14]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*14)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL15]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*15)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineL16]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*16)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineL17]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*17)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineL18]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*18)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineL19]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.125)
RotationAngle = (PI/-1.68) + (0.096*19)
MeterStyle = RMSStyle
LineColor = #RMSHi#

;Left-hand RMS
[MeterRMSLineR0]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR1]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*1)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR2]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*2)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR3]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*3)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR4]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*4)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR5]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*5)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR6]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*6)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR7]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*7)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR8]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*8)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR9]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*9)
MeterStyle = RMSStyle
LineColor = #RMSLow#
[MeterRMSLineR10]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*10)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR11]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*11)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR12]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*12)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR13]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*13)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR14]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*14)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR15]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*15)
MeterStyle = RMSStyle
LineColor = #RMSMid#
[MeterRMSLineR16]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*16)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineR17]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*17)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineR18]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*18)
MeterStyle = RMSStyle
LineColor = #RMSHi#
[MeterRMSLineR19]
Meter = Roundline
UpdateDivider = -1
StartAngle = (PI*3.098)
RotationAngle = (PI/-1.60) - (0.096*19)
MeterStyle = RMSStyle
LineColor = #RMSHi#